match_period_length_seconds: 300
current_delay: 0
match_sets:
    - start_time: 2014-04-26 13:00:00
      end_time: 2014-04-26 17:30:00

    - start_time: 2014-04-27 09:30:00
      end_time: 2014-04-27 12:15:00

    - start_time: 2014-04-27 13:15:00
      end_time: 2014-04-27 15:00:00
matches:
    0:
        arena_0: [ABC, SRZ, QEH, PSC]
        arena_1: [DFE, BDJ, LPQ, MRH]
    1:
        arena_0: [PNY, BCC, PSA, PSC]
        arena_1: [DFE, BDJ, LPQ, MRH]
